from PyQt6.QtCore import Qt, QEvent
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import QMainWindow, QWidget, QVBoxLayout, QGroupBox, QHBoxLayout, QLabel, QLineEdit, QPushButton, \
    QComboBox, QCheckBox, QApplication, QSpinBox

from src.UI.UI_widgets.list_view import ListView


class MainWindow(QMainWindow):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setObjectName("mainWindow")
        self.setWindowTitle("Image Converter")
        self.setCentralWidget(self.create_gui())

    def create_gui(self) -> QWidget:
        central_widget = QWidget()
        main_layout = QVBoxLayout()
        self.title_label = QLabel("Title")
        self.title_label.setObjectName("titleLabel")
        self.title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title_label.setFont(QFont("Arial", 20))
        self.images_group = QGroupBox("Images")
        self.images_group.setObjectName("imagesGroup")
        images_layout = QHBoxLayout()
        self.image_path_text = QLabel("Select path:")
        self.image_path_text.setObjectName("imagePathLabel")
        self.image_path_edit = QLineEdit()
        self.image_path_edit.setObjectName("imagePathEdit")
        self.image_path_edit.setReadOnly(True)
        self.image_path_edit.setPlaceholderText("Selected path...")
        self.image_button = QPushButton("Select")
        self.image_button.setObjectName("imageButton")
        self.list_view = ListView()
        self.output_group = QGroupBox("Output")
        self.output_group.setObjectName("outputGroup")
        output_layout = QHBoxLayout()
        self.output_path_label = QLabel("Select output:")
        self.output_path_label.setObjectName("outputPathLabel")
        self.output_path_edit = QLineEdit()
        self.output_path_edit.setObjectName("outputPathEdit")
        self.output_path_edit.setReadOnly(True)
        self.output_path_edit.setPlaceholderText("Selected output...")
        self.output_path_button = QPushButton("Select")
        self.output_path_button.setObjectName("outputButton")
        self.options_group = QGroupBox("Options")
        self.options_group.setObjectName("optionsGroup")
        options_layout = QVBoxLayout()
        self.format_group = QGroupBox("Format")
        self.format_group.setObjectName("formatGroup")
        format_layout = QHBoxLayout()
        self.format_label = QLabel("Format:")
        self.format_label.setObjectName("formatLabel")
        self.format_combobox = QComboBox()
        self.format_combobox.setObjectName("formatComboBox")
        self.resize_group = QGroupBox("Resize")
        self.resize_group.setObjectName("resizeGroup")
        resize_layout = QVBoxLayout()
        size_layout = QHBoxLayout()
        self.width_label = QLabel("Width:")
        self.width_label.setObjectName("widthLabel")
        self.width_spinbox = QSpinBox()
        self.width_spinbox.setObjectName("widthSpinbox")
        self.height_label = QLabel("Height:")
        self.height_label.setObjectName("heightLabel")
        self.height_spinbox = QSpinBox()
        self.height_spinbox.setObjectName("heightSpinbox")
        ratio_layout = QHBoxLayout()
        self.ratio_label = QLabel("Ratio:")
        self.ratio_label.setObjectName("ratioLabel")
        self.ratio_checkbox = QCheckBox()
        self.ratio_checkbox.setObjectName("ratioCheckbox")
        convert_layout = QHBoxLayout()
        self.convert_button = QPushButton("Convert")
        self.convert_button.setObjectName("convertButton")
        images_layout.addWidget(self.image_path_text)
        images_layout.addWidget(self.image_path_edit)
        images_layout.addWidget(self.image_button)
        output_layout.addWidget(self.output_path_label)
        output_layout.addWidget(self.output_path_edit)
        output_layout.addWidget(self.output_path_button)
        format_layout.addWidget(self.format_label)
        format_layout.addWidget(self.format_combobox)
        size_layout.addWidget(self.width_label)
        size_layout.addWidget(self.width_spinbox)
        size_layout.addWidget(self.height_label)
        size_layout.addWidget(self.height_spinbox)
        ratio_layout.addWidget(self.ratio_label)
        ratio_layout.addWidget(self.ratio_checkbox)
        ratio_layout.addStretch()
        resize_layout.addLayout(size_layout)
        resize_layout.addLayout(ratio_layout)
        self.format_group.setLayout(format_layout)
        self.resize_group.setLayout(resize_layout)
        options_layout.addWidget(self.format_group)
        options_layout.addWidget(self.resize_group)
        convert_layout.addStretch()
        convert_layout.addWidget(self.convert_button)
        convert_layout.addStretch()
        self.images_group.setLayout(images_layout)
        self.output_group.setLayout(output_layout)
        self.options_group.setLayout(options_layout)
        main_layout.addWidget(self.title_label)
        main_layout.addWidget(self.images_group)
        main_layout.addWidget(self.list_view)
        main_layout.addWidget(self.output_group)
        main_layout.addWidget(self.options_group)
        main_layout.addLayout(convert_layout)
        central_widget.setLayout(main_layout)
        return central_widget

    def showEvent(self, event: QEvent) -> None:
        screen = QApplication.primaryScreen()
        geometry = screen.availableGeometry()
        width = self.width()
        height = self.height()
        self.setFixedSize(width, height)
        self.move((geometry.width() - width) // 2, (geometry.height() - height) // 2)